import numpy as np
import pytest
from scipy.stats import chisquare

from lwe.params import DEFAULT_PARAMS, LWEParams
from lwe.modular import mod_add, mod_matmul
from lwe.sampler import sample_gaussian, sample_uniform

from kem.keygen import keygen
from kem.kem import encaps, decaps
from kem.kdf import derive_key

def test_keygen_shapes():
    #check if the keys generated have the correct shapes
    params = DEFAULT_PARAMS
    pk, sk = keygen(params)
    assert pk[0].shape == (params.m, params.n)
    assert pk[1].shape == (params.m,)
    assert sk.shape == (params.n,)


def test_keygen_range():
    #check if the keys generated are in the correct range
    params = DEFAULT_PARAMS
    pk, sk = keygen(params)
    assert np.all(pk[0] >= 0) and np.all(pk[0] < params.q)
    assert np.all(pk[1] >= 0) and np.all(pk[1] < params.q)
    assert np.all(sk >= 0) and np.all(sk < params.q)


def test_encaps_shape():
    #check if the cyphertext generated has the correct shape
    params = DEFAULT_PARAMS
    pk, sk = keygen(params)
    cyphertext, mu = encaps(pk, params)
    assert cyphertext[0].shape == (params.n, params.n)
    assert cyphertext[1].shape == (params.n,)
    assert mu.shape == (params.n,)


def test_encaps_mu_binary():
    #check if mu is a binary 
    params = DEFAULT_PARAMS
    pk, sk = keygen(params)
    cyphertext, mu = encaps(pk, params)
    assert np.all((mu == 0) | (mu == 1))


def test_correctness():
    #check if the shared secret derived from the cyphertext is the same as the one generated by encaps
    params = DEFAULT_PARAMS
    pk, sk = keygen(params)
    cyphertext, mu = encaps(pk, params)
    recovered = decaps(cyphertext, sk, params)
    assert np.array_equal(mu, recovered)


def test_failure_rate():
    #check the failure rate of the encaps/decaps protocol
    #there is always a small probability of failing in PKC
    #unfortunetly, this takes a lot of time to run  :/
    #I tried storing everything to be faster, but then I did not have space :/
    #whatever...
    params = DEFAULT_PARAMS
    trials = int(1e4)
    failures = 0
    pk, sk = keygen(params)
    for _ in range(trials):
        cyphertext, mu = encaps(pk, params)
        recovered = decaps(cyphertext, sk, params)
        if not np.array_equal(mu, recovered):
            failures += 1
    failure_rate = failures / trials
    assert failure_rate < 1e-3 

